#!/bin/bash
# Turn notification script — sends rich game stats email to all players
# Reads rankings from status.json (generated by generate_status_json.sh)
# Called by start.sh's turn monitoring process
# Usage: turn_notify.sh <turn_number> <year>

TURN="$1"
YEAR="$2"
TEST_TO=""
shift 2 || true
for arg in "$@"; do
  case "$arg" in
    --to=*) TEST_TO="${arg#--to=}" ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/lib_log.sh"
_notify_started=$(date +%s)
plog turn-notify "BEGIN turn=${TURN} year=${YEAR} (pid=$$)"
trap '_rc=$?; plog turn-notify "END turn=${TURN} rc=${_rc} ($(( $(date +%s) - _notify_started ))s)"' EXIT
SES_SMTP_USER="${SES_SMTP_USER:-}"
SES_SMTP_PASS="${SES_SMTP_PASS:-}"
SES_SMTP_HOST="${SES_SMTP_HOST:-email-smtp.us-east-1.amazonaws.com}"
FROM_EMAIL="${FROM_EMAIL:-freeciv@andrewmcgrath.info}"
SERVER_HOST="${SERVER_HOST:-freeciv.andrewmcgrath.info}"
CC_EMAIL="${CC_EMAIL:-}"
DB_PATH="/data/saves/freeciv.sqlite"
STATUS_JSON="${WEBROOT:-/opt/freeciv/www}/status.json"
GAZETTE_JSON="${SAVE_DIR:-/data/saves}/gazette.json"

echo "[turn_notify] Turn $TURN (Year $YEAR) — starting notification process"

# Check if emails are enabled
EMAIL_ENABLED=$(cat /opt/freeciv/email_enabled.settings 2>/dev/null | tr -d '[:space:]')
if [ "$EMAIL_ENABLED" != "true" ]; then
  echo "[turn_notify] Emails disabled (email_enabled.settings != true), skipping"
  exit 0
fi

if [ -z "$SES_SMTP_USER" ] || [ -z "$SES_SMTP_PASS" ]; then
  echo "[turn_notify] No SES SMTP credentials set, skipping email notifications"
  exit 0
fi

if [ ! -f "$DB_PATH" ]; then
  echo "[turn_notify] Database not found at $DB_PATH, skipping notifications"
  exit 0
fi

# ============================================================
# Calculate turn deadline (23 hours from now)
# ============================================================
DEADLINE_EST=$(TZ='America/New_York' date -d '+23 hours' '+%a %b %-d, %-I:%M %p' 2>/dev/null || TZ='America/New_York' date -v+23H '+%a %b %-d, %-I:%M %p' 2>/dev/null || echo "~23 hours from now")
DEADLINE_UTC=$(date -u -d '+23 hours' '+%a %b %-d, %-I:%M %p' 2>/dev/null || date -u -v+23H '+%a %b %-d, %-I:%M %p' 2>/dev/null || echo "~23 hours from now")

# ============================================================
# Read game stats from status.json
# ============================================================
RANKINGS_ROWS=""
YEAR_DISPLAY=""
TURNS_PLAYED=$((TURN - 1))

# Track whether status.json is internally consistent with the turn we were
# asked to notify for. When it isn't, we drop the year from the subject line
# (better than shipping "Year 0 AD") and skip the rankings block.
STATUS_VALID=false

if [ -f "$STATUS_JSON" ] && jq . "$STATUS_JSON" >/dev/null 2>&1; then
  echo "[turn_notify] Reading stats from $STATUS_JSON"

  # Sanity: refuse to use status.json if it doesn't match the turn we were
  # told about, or if the year defaulted to 0 (sentinel for "save file
  # couldn't be parsed"). This prevents the "Turn N — Year 0 AD" emails that
  # happen when generate_status_json.sh races with a save write.
  JSON_TURN=$(jq -r '.game.turn // 0' "$STATUS_JSON")
  JSON_YEAR=$(jq -r '.game.year // 0' "$STATUS_JSON")

  if [ "$JSON_TURN" = "$TURN" ] && [ "$JSON_YEAR" != "0" ] && [ "$JSON_YEAR" != "null" ]; then
    STATUS_VALID=true
    YEAR_DISPLAY=$(jq -r '.game.year_display' "$STATUS_JSON")
    YEAR="$JSON_YEAR"
  else
    echo "[turn_notify] WARNING: status.json turn=$JSON_TURN year=$JSON_YEAR does not match expected turn=$TURN — skipping rankings/year"
  fi
fi

if [ "$STATUS_VALID" = "true" ]; then

  # Build rankings rows from players array (already sorted by rank)
  NUM_PLAYERS=$(jq '.players | length' "$STATUS_JSON")

  for idx in $(seq 0 $((NUM_PLAYERS - 1))); do
    name=$(jq -r ".players[$idx].name" "$STATUS_JSON")
    nation=$(jq -r ".players[$idx].nation" "$STATUS_JSON")
    score=$(jq -r ".players[$idx].score" "$STATUS_JSON")
    ncities=$(jq -r ".players[$idx].cities" "$STATUS_JSON")
    nunits=$(jq -r ".players[$idx].units" "$STATUS_JSON")
    gold=$(jq -r ".players[$idx].gold" "$STATUS_JSON")
    gov=$(jq -r ".players[$idx].government" "$STATUS_JSON")
    is_alive=$(jq -r ".players[$idx].is_alive" "$STATUS_JSON")
    rank=$(jq -r ".players[$idx].rank" "$STATUS_JSON")

    # Score color by rank
    case $rank in
      1) rank_cell="<span style='font-size:16px;'>&#x1F947;</span>"
         score_color="#ffd700" row_bg="#12284a" name_color="#fff" ;;
      2) rank_cell="<span style='font-size:16px;'>&#x1F948;</span>"
         score_color="#c0c0c0" row_bg="" name_color="#fff" ;;
      3) rank_cell="<span style='font-size:16px;'>&#x1F949;</span>"
         score_color="#cd7f32" row_bg="rgba(255,255,255,0.02)" name_color="#fff" ;;
      *) rank_cell="<span style='color:#537895;font-weight:bold;'>${rank}</span>"
         score_color="#aaa" name_color="#ddd"
         if [ $((rank % 2)) -eq 0 ]; then row_bg=""; else row_bg="rgba(255,255,255,0.02)"; fi ;;
    esac

    # Dead player styling
    if [ "$is_alive" = "false" ]; then
      name_color="#666"
      score_color="#666"
      name="${name} &#x1F480;"
    fi

    row_style=""
    [ -n "$row_bg" ] && row_style="background:${row_bg};"

    RANKINGS_ROWS="${RANKINGS_ROWS}
        <tr style='${row_style}'>
          <td style='padding:10px 6px;text-align:center;border-bottom:1px solid #2a2a4a;'>${rank_cell}</td>
          <td style='padding:10px 6px;border-bottom:1px solid #2a2a4a;'><strong style='color:${name_color};font-size:14px;'>${name}</strong><br><span style='color:#537895;font-size:11px;'>${nation} &middot; ${gov}</span></td>
          <td style='padding:10px 6px;text-align:center;border-bottom:1px solid #2a2a4a;color:${score_color};font-weight:bold;font-size:16px;'>${score}</td>
          <td style='padding:10px 6px;text-align:center;border-bottom:1px solid #2a2a4a;color:#ccc;'>${ncities}</td>
          <td style='padding:10px 6px;text-align:center;border-bottom:1px solid #2a2a4a;color:#ccc;'>${nunits}</td>
          <td style='padding:10px 6px;text-align:right;border-bottom:1px solid #2a2a4a;color:#f0c040;'>${gold}</td>
        </tr>"
  done
else
  echo "[turn_notify] WARNING: status.json not found or invalid, sending email without rankings"
fi

# ============================================================
# Read latest gazette entry
# ============================================================
# Only include the gazette if (a) the publishing marker is clear — start.sh
# removes it after generate_gazette.sh finishes — and (b) the newest gazette
# entry describes turn N-1 (the turn we were just notified about is N). If
# either check fails, we ship rankings-only rather than shipping a stale
# edition branded with the current turn.
GAZETTE_HTML=""
GAZETTE_PUBLISHING_FILE="${GAZETTE_PUBLISHING_FILE:-${SAVE_DIR:-/data/saves}/gazette-publishing}"
EXPECTED_GZ_TURN=$((TURN - 1))
GAZETTE_READY=true
if [ -f "$GAZETTE_PUBLISHING_FILE" ]; then
  echo "[turn_notify] WARNING: gazette publishing marker present — skipping gazette block"
  GAZETTE_READY=false
fi

if [ "$GAZETTE_READY" = "true" ] && [ -f "$GAZETTE_JSON" ] && jq . "$GAZETTE_JSON" >/dev/null 2>&1; then
  GAZETTE_ENTRY=$(jq -r '.[-1] // empty' "$GAZETTE_JSON")
  if [ -n "$GAZETTE_ENTRY" ]; then
    GZ_ENTRY_TURN=$(echo "$GAZETTE_ENTRY" | jq -r '.turn // 0')
    if [ "$GZ_ENTRY_TURN" != "$EXPECTED_GZ_TURN" ]; then
      echo "[turn_notify] WARNING: latest gazette is turn $GZ_ENTRY_TURN, expected $EXPECTED_GZ_TURN — skipping gazette block"
      GAZETTE_ENTRY=""
    fi
  fi
  if [ -n "$GAZETTE_ENTRY" ]; then
    GZ_HEADLINE=$(echo "$GAZETTE_ENTRY" | jq -r '.headline // empty')
    GZ_YEAR=$(echo "$GAZETTE_ENTRY" | jq -r '.year_display // empty')
    GZ_HAS_SECTIONS=$(echo "$GAZETTE_ENTRY" | jq -r 'if .sections then "yes" else "no" end')

    if [ -n "$GZ_HEADLINE" ] && [ "$GZ_HAS_SECTIONS" = "yes" ]; then
      # New multi-section format — show front page teaser + link to full issue
      GZ_FRONT=$(echo "$GAZETTE_ENTRY" | jq -r '.sections.front_page.content // .sections.front_page // empty')
      GZ_FRONT_BY=$(echo "$GAZETTE_ENTRY" | jq -r '.sections.front_page.byline // empty')
      GZ_TURN=$(echo "$GAZETTE_ENTRY" | jq -r '.turn // empty')
      GZ_IMG=$(echo "$GAZETTE_ENTRY" | jq -r '.illustration // empty')
      GZ_IMG_CREDIT=$(echo "$GAZETTE_ENTRY" | jq -r '.illustration_caption.credit // empty')
      GZ_IMG_DESC=$(echo "$GAZETTE_ENTRY" | jq -r '.illustration_caption.description // empty' | sed 's/<[^>]*>//g')

      GAZETTE_HTML="
    <div style='background:#f5f0e6;border:none;padding:0;margin:0 0 24px 0;font-family:Georgia,Times New Roman,serif;color:#1a1a1a;'>
      <div style='text-align:center;padding:20px 24px 12px;border-bottom:4px double #1a1a1a;'>
        <div style='font-size:36px;font-weight:900;color:#1a1a1a;letter-spacing:2px;font-family:Georgia,serif;line-height:1;'>The Civ Chronicle</div>
        <div style='font-size:10px;color:#666;text-transform:uppercase;letter-spacing:4px;margin-top:6px;'>All the civilization that&rsquo;s fit to print</div>
      </div>
      <div style='display:flex;justify-content:space-between;font-size:10px;color:#666;text-transform:uppercase;letter-spacing:1px;padding:6px 24px;border-bottom:1px solid #ccc;'>
        <span>Turn ${GZ_TURN}</span><span>${GZ_YEAR}</span><span>Vol. I, No. ${GZ_TURN}</span>
      </div>
      <div style='font-size:24px;font-weight:900;color:#1a1a1a;line-height:1.2;letter-spacing:-0.5px;font-family:Georgia,serif;text-align:center;padding:18px 24px 6px;'>${GZ_HEADLINE}</div>
      <div style='font-size:11px;color:#666;text-align:center;font-style:italic;padding:0 24px 14px;border-bottom:1px solid #ccc;'>${GZ_FRONT_BY}</div>
      <div style='padding:14px 24px;font-size:13px;line-height:1.7;color:#2a2a2a;text-align:justify;overflow:hidden;'>$([ -n "$GZ_IMG" ] && echo "<div style='float:right;width:160px;margin:0 0 10px 14px;'><img src='https://${SERVER_HOST}/${GZ_IMG}' alt='Chronicle illustration' width='160' style='width:160px;height:auto;border:1px solid #999;display:block;' /><div style='font-size:8px;color:#888;text-align:center;margin-top:4px;line-height:1.3;'><em>${GZ_IMG_DESC}</em><br>${GZ_IMG_CREDIT}</div></div>")${GZ_FRONT}</div>
      <div style='text-align:center;padding:12px 24px 18px;border-top:1px solid #ccc;'>
        <a href='https://${SERVER_HOST}/#gazette' style='display:inline-block;background:#1a1a1a;color:#f5f0e6;padding:10px 28px;font-size:13px;font-weight:700;text-decoration:none;font-family:Georgia,serif;'>Read the full issue &rarr;</a>
      </div>
      <div style='text-align:center;padding:8px;border-top:4px double #1a1a1a;font-size:9px;color:#888;text-transform:uppercase;letter-spacing:2px;'>The Civ Chronicle</div>
    </div>"
      echo "[turn_notify] Including gazette in email: $GZ_HEADLINE"
    elif [ -n "$GZ_HEADLINE" ]; then
      # Old single-article format fallback
      GZ_ARTICLE=$(echo "$GAZETTE_ENTRY" | jq -r '.article // empty')
      if [ -n "$GZ_ARTICLE" ]; then
        GAZETTE_HTML="
    <div style='background:#111827;border:1px solid #2a2a4a;border-radius:8px;padding:20px 24px;margin:0 0 24px 0;'>
      <div style='color:#e94560;font-size:10px;text-transform:uppercase;letter-spacing:2px;font-weight:700;margin-bottom:8px;'>The Civ Chronicle</div>
      <div style='color:#fff;font-size:17px;font-weight:800;line-height:1.3;margin-bottom:4px;'>${GZ_HEADLINE}</div>
      <div style='color:#537895;font-size:11px;margin-bottom:14px;'>${GZ_YEAR}</div>
      <div style='color:#b0bdd0;font-size:13px;line-height:1.7;'>${GZ_ARTICLE}</div>
    </div>"
        echo "[turn_notify] Including gazette in email: $GZ_HEADLINE"
      fi
    fi
  fi
fi

# Year display fallback — only if we have a real, non-zero year from a valid
# status.json. If STATUS_VALID is false, we omit the year from the subject
# rather than ship a made-up one (previously the code happily emitted "0 AD").
if [ "$STATUS_VALID" != "true" ] || [ -z "$YEAR_DISPLAY" ] || [ "$YEAR_DISPLAY" = "null" ]; then
  YEAR_DISPLAY=""
fi

# ============================================================
# Send emails to all registered players
# ============================================================

if [ -n "$TEST_TO" ]; then
  echo "[turn_notify] TEST MODE — sending only to $TEST_TO"
  EMAILS="TestPlayer|${TEST_TO}"
else
  EMAILS=$(sqlite3 "$DB_PATH" "SELECT name, email FROM fcdb_auth WHERE email IS NOT NULL AND email != '';" 2>/dev/null)
fi

if [ -z "$EMAILS" ]; then
  echo "[turn_notify] No players with email addresses found"
  exit 0
fi

echo "$EMAILS" | while IFS='|' read -r NAME EMAIL; do
  [ -z "$EMAIL" ] && continue
  echo "[turn_notify] Sending to $NAME ($EMAIL)"

  if [ -n "$YEAR_DISPLAY" ]; then
    SUBJECT="Turn $TURN — Year $YEAR_DISPLAY — Your move, $NAME!"
  else
    SUBJECT="Turn $TURN — Your move, $NAME!"
  fi

  EMAIL_MSG=$(cat <<EMAILEOF
From: Freeciv Server <$FROM_EMAIL>
To: $EMAIL
$([ -n "$CC_EMAIL" ] && echo "Cc: $CC_EMAIL")
Subject: $SUBJECT
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#0f0f1a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,sans-serif;">
<div style="max-width:600px;margin:0 auto;background:#1a1a2e;color:#e0e0e0;">

  <div style="background:#0f3460;padding:20px 24px;text-align:center;">
    <div style="font-size:14px;letter-spacing:2px;text-transform:uppercase;color:#537895;margin-bottom:4px;">Freeciv Longturn</div>
    <div style="font-size:28px;font-weight:800;color:#fff;">Turn ${TURN}</div>
    <div style="font-size:15px;color:#8eaccd;margin-top:2px;">$([ -n "$YEAR_DISPLAY" ] && echo "${YEAR_DISPLAY} &middot; ")${TURNS_PLAYED} turns played</div>
  </div>

  <div style="padding:24px;">
    <p style="font-size:15px;color:#ccc;margin:0 0 20px 0;">Hey <strong style="color:#fff;">${NAME}</strong> &mdash; a new turn is ready.</p>

    ${GAZETTE_HTML}

    <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;font-size:13px;">
      <thead>
        <tr>
          <th style="padding:8px 6px;text-align:center;color:#537895;font-size:11px;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #2a2a4a;" width="36">#</th>
          <th style="padding:8px 6px;text-align:left;color:#537895;font-size:11px;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #2a2a4a;">Player</th>
          <th style="padding:8px 6px;text-align:center;color:#537895;font-size:11px;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #2a2a4a;" width="52">Score</th>
          <th style="padding:8px 6px;text-align:center;color:#537895;font-size:11px;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #2a2a4a;" width="48">Cities</th>
          <th style="padding:8px 6px;text-align:center;color:#537895;font-size:11px;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #2a2a4a;" width="48">Units</th>
          <th style="padding:8px 6px;text-align:right;color:#537895;font-size:11px;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #2a2a4a;" width="52">Gold</th>
        </tr>
      </thead>
      <tbody>
        ${RANKINGS_ROWS}
      </tbody>
    </table>

    <div style="text-align:center;margin:28px 0 20px 0;">
      <div style="background:#e94560;color:#fff;display:inline-block;padding:12px 28px;border-radius:6px;font-size:15px;font-weight:bold;letter-spacing:0.3px;">Play Your Turn</div>
      <div style="color:#537895;font-size:12px;margin-top:8px;">${SERVER_HOST} &middot; port 5556</div>
    </div>

    <div style="background:#1e2a45;border-radius:6px;padding:14px 16px;margin:12px 0;border-left:3px solid #e94560;">
      <div style="color:#e94560;font-weight:bold;font-size:13px;margin-bottom:4px;">Turn Deadline</div>
      <div style="color:#ccc;font-size:13px;">${DEADLINE_EST} EST</div>
      <div style="color:#7a8fa6;font-size:12px;">${DEADLINE_UTC} UTC</div>
    </div>

    <div style="background:#1e2a45;border-radius:6px;padding:14px 16px;margin:12px 0;border-left:3px solid #4caf50;">
      <div style="color:#a5d6a7;font-weight:bold;font-size:13px;margin-bottom:3px;">Remember: click Turn Done when finished</div>
      <div style="color:#7a8fa6;font-size:12px;">If all players click it, the next turn starts immediately.</div>
    </div>

    <div style="text-align:center;margin:20px 0 8px 0;">
      <a href="https://${SERVER_HOST}" style="color:#537895;font-size:12px;">View full stats, history graphs &amp; game rules at <strong style="color:#8eaccd;">${SERVER_HOST}</strong></a>
      <br><a href="https://${SERVER_HOST}/changelog.html" style="color:#537895;font-size:12px;">What's new? <strong style="color:#e94560;">View changelog</strong></a>
    </div>

  </div>

  <div style="padding:16px 24px;text-align:center;border-top:1px solid #2a2a4a;">
    <span style="color:#3a3a5a;font-size:11px;">Freeciv Longturn Server &middot; <a href="https://${SERVER_HOST}" style="color:#3a3a5a;">${SERVER_HOST}</a></span>
  </div>

</div>
</body>
</html>
EMAILEOF
)

  echo "$EMAIL_MSG" | curl -s --url "smtps://$SES_SMTP_HOST:465" \
    --ssl-reqd \
    --mail-from "$FROM_EMAIL" \
    --mail-rcpt "$EMAIL" \
    ${CC_EMAIL:+--mail-rcpt "$CC_EMAIL"} \
    --user "$SES_SMTP_USER:$SES_SMTP_PASS" \
    --upload-file - 2>&1

  if [ $? -eq 0 ]; then
    echo "[turn_notify] Sent to $EMAIL"
  else
    echo "[turn_notify] Failed to send to $EMAIL"
  fi
done

echo "[turn_notify] Done sending turn $TURN notifications"
